### ISSUE TITLE
resources not tracked by state

### ISSUE THREAD

**Issue by konstantinoskonstantinidis** [QuiNovas/terraform-aws-cloudfront#36]
I run into this issue when I try to reapply the module :

Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/lambda/<name>-default-index-redirector' already exists.
│
│   with module.cloudfront.aws_cloudwatch_log_group.redirector_log_group,
│   on .terraform/modules/cloudfront/default-index-redirect.tf line 21, in resource "aws_cloudwatch_log_group" "redirector_log_group":
│   21: resource "aws_cloudwatch_log_group" "redirector_log_group" {

 Error: error creating Lambda Function (1): ResourceConflictException: Function already exist: <name>-default-index-redirector
│ {
│   RespMetadata: {
│     StatusCode: 409,
│     RequestID: "e15661c5-254b-41dc-a6ce-d207d460bf28"
│   },
│   Message_: "Function already exist: <name>-default-index-redirector",
│   Type: "User"
│ }
│
│   with module.cloudfront.aws_lambda_function.redirector,
│   on .terraform/modules/cloudfront/default-index-redirect.tf line 45, in resource "aws_lambda_function" "redirector":
│   45: resource "aws_lambda_function" "redirector" {

and if I try to import that into the state with:

$terraform import aws_lambda_function.redirector <name>-default-index-redirector , I get : 

resource address "aws_lambda_function.redirector" does not exist in the configuration.

Before importing this resource, please create its configuration in the root module. For example:

resource "aws_lambda_function" "redirector" {
  # (resource arguments)
}

which means that module is creating the resource but is untracked by the state, so next time i try to apply code it cannot create those resources since they are already existing

**Comment by joseph-wortmann** [comment]
Can you supply the code that is calling this module? From your output it appears that you are providing an empty `distribution_name`, and that is not how the module was designed to be used...

**Comment by konstantinoskonstantinidis** [comment]
I removed the $var.name-$terraform.workspace from the logs above for security reasons. Nevertheless, here's my code:


module "cloudfront" {
  source = "QuiNovas/cloudfront/aws"
  version = "4.0.1"

  aliases               = var.aliases[terraform.workspace]
  acm_certificate_arn   = aws_acm_certificate.cert_us.id
  distribution_name     = "${var.name}-${terraform.workspace}"
  log_bucket            = aws_s3_bucket.logs.id
  web_acl_id            = aws_waf_web_acl.waf_acl.id
  bucket_name           = "${var.name}-${terraform.workspace}-bucketname"
  custom_error_response = var.custom_error_response

  ordered_cache_behavior = [
    {
      allowed_methods             = ["GET", "HEAD"]
      cached_methods              = ["GET", "HEAD"]
      default_ttl                 = 0
      max_ttl                     = 0
      min_ttl                     = 0
      compress                    = false
      field_level_encryption_id   = null
      target_origin_id            = "${var.name}-${terraform.workspace}"
      lambda_function_association = []
      path_pattern                = "index.html"
      smooth_streaming            = false
      trusted_signers             = []
      viewer_protocol_policy      = "redirect-to-https"
      forwarded_values = {
        headers                 = []
        query_string            = false
        query_string_cache_keys = []
        cookies = {
          forward           = "none"
          whitelisted_names = []
        }

      }
    }
  ]

  tags = {
    Name        = "frontend"
    Environment = terraform.workspace
  }
}

**Comment by joseph-wortmann** [comment]
Hmm... Something must be wrong with your state file. The resource is obviously being created but not stored in the state file, and that is a function of terraform not of a module.
